export const voidTags: Set<string> = new Set([
	"area",
	"base",
	"br",
	"col",
	"embed",
	"hr",
	"img",
	"input",
	"link",
	"meta",
	"param",
	"source",
	"track",
	"wbr",
]);

export const booleanAttributes: Set<string> = new Set([
	"allowfullscreen",
	"async",
	"autofocus",
	"autoplay",
	"checked",
	"controls",
	"default",
	"defer",
	"disabled",
	"download",
	"formnovalidate",
	"hidden",
	"inert",
	"ismap",
	"itemscope",
	"loop",
	"multiple",
	"muted",
	"nomodule",
	"novalidate",
	"open",
	"playsinline",
	"readonly",
	"required",
	"reversed",
	"selected",
]);

/** Maps DOM property names to HTML attribute names for rendering. */
export const attributeAliases: Map<string, string> = new Map([
	["acceptCharset", "accept-charset"],
	["autoFocus", "autofocus"],
	["autoPlay", "autoplay"],
	["charSet", "charset"],
	["className", "class"],
	["colSpan", "colspan"],
	["crossOrigin", "crossorigin"],
	["dateTime", "datetime"],
	["fetchPriority", "fetchpriority"],
	["formAction", "formaction"],
	["formEncType", "formenctype"],
	["formMethod", "formmethod"],
	["formNoValidate", "formnovalidate"],
	["formTarget", "formtarget"],
	["htmlFor", "for"],
	["httpEquiv", "http-equiv"],
	["itemProp", "itemprop"],
	["maxLength", "maxlength"],
	["minLength", "minlength"],
	["noModule", "nomodule"],
	["playsInline", "playsinline"],
	["readOnly", "readonly"],
	["rowSpan", "rowspan"],
	["srcDoc", "srcdoc"],
	["srcSet", "srcset"],
	["tabIndex", "tabindex"],
]);

export const unitlessStyleProperties: Set<string> = new Set([
	"animation-iteration-count",
	"aspect-ratio",
	"border-image-outset",
	"border-image-slice",
	"border-image-width",
	"box-flex",
	"box-flex-group",
	"box-ordinal-group",
	"column-count",
	"columns",
	"flex",
	"flex-grow",
	"flex-negative",
	"flex-order",
	"flex-positive",
	"flex-shrink",
	"flood-opacity",
	"font-weight",
	"grid-area",
	"grid-column",
	"grid-column-end",
	"grid-column-span",
	"grid-column-start",
	"grid-row",
	"grid-row-end",
	"grid-row-span",
	"grid-row-start",
	"line-clamp",
	"line-height",
	"opacity",
	"order",
	"orphans",
	"scale",
	"stop-opacity",
	"stroke-dasharray",
	"stroke-dashoffset",
	"stroke-miterlimit",
	"stroke-opacity",
	"stroke-width",
	"tab-size",
	"widows",
	"z-index",
	"zoom",
]);

export const invalidAttributeNameCodes: Set<number> = new Set([
	0x20, 0x22, 0x27, 0x2f, 0x3c, 0x3d, 0x3e, 0x5c, 0x60,
]);

export const invalidStylePropertyNameCodes: Set<number> = new Set([
	0x20, 0x22, 0x27, 0x28, 0x29, 0x2f, 0x3a, 0x3b, 0x5b, 0x5c, 0x5d, 0x7b, 0x7d,
]);
